extends: default

rules:
  document-start: disable
  line-length:
    allow-non-breakable-inline-mappings: true
    allow-non-breakable-words: true
    max: 80

ignore: |
  testing/example-with-metadata.yml
  testing/expect.yml
