name: dwalk

on:  # yamllint disable-line rule:truthy
  - push

jobs:

  build:
    container: cariad/ci:1.0.0
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"

    steps:
      - uses: actions/checkout@v2

      - name: Create Python virtual environment
        run: pipenv --python ${{ matrix.python-version }}

      - name: Sync dependencies
        run: pipenv sync --dev

      - name: Lint
        run: ./lint.sh

      - name: Test
        run: ./test.sh

      - name: Version
        run: echo "${GITHUB_REF##*/}" > corf/VERSION

      - name: Build
        run: ./build.sh

      - name: CLI test
        run: |
          pip install "dist/$(ls dist/*.whl)"

          dwalk --version | tee version.tmp
          grep -qF "${GITHUB_REF##*/}" version.tmp

          cd testing/bottom
          dwalk --filenames dwalk.2.yml dwalk.1.yml

      - name: Archive distributable
        if: ${{ matrix.python-version }} == "3.9"
        uses: actions/upload-artifact@v2
        with:
          name: distributable
          path: dist
          retention-days: 1

  publish:
    if: startsWith(github.ref, 'refs/tags')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build distributable
        uses: actions/download-artifact@v2
        with:
          name: distributable

      - name: Create distributable directory
        run: |
          mkdir dist
          cp *.whl dist
          ls -al dist/

      - name: Publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
